#!/bin/sh

# Check if "sxhkd" and "bar" are running, if not, run them in background
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x bar > /dev/null || bar &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config focused_border_color "#009F6B"
bspc config window_gap           12
bspc config top_padding	         24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle true 
